name: MSDO Sample Workflow
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  security-events: write
  contents: read

jobs:
  sample:
    name: MSDO on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false # Prevents one OS failure from stopping the other
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@v1
        id: msdo

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3 # Updated v2 -> v3
        if: always()
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      - name: Upload alerts file as a workflow artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:  
          # Adding the OS name to the artifact prevents the (409) Conflict error
          name: alerts-${{ matrix.os }} 
          path: ${{ steps.msdo.outputs.sarifFile }}
