name: MSDO Sample Workflow
on:
  push:
    branches:
      - main

permissions:
  id-token: write      # Required for federation
  security-events: write # Required for SARIF upload
  contents: read       # REQUIRED to allow the runner to checkout code

jobs:
  sample:
    name: MSDO on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4 for better stability

      # 2. Run analyzers
      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@v1
        id: msdo

      # 3. Upload alerts to the Security tab
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always() # Ensures upload even if previous steps find vulnerabilities
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # 4. Upload alerts file as a workflow artifact
      - name: Upload alerts file as a workflow artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:  
          name: alerts-${{ matrix.os }} # Unique name per OS to avoid conflict
          path: ${{ steps.msdo.outputs.sarifFile }}
